# shellcheck disable=all
# --- XDG ---
XDG_DATA_HOME=$HOME/.local/share
XDG_CONFIG_HOME=$HOME/.config
XDG_STATE_HOME=$HOME/.local/state
XDG_CACHE_HOME=$HOME/.cache

NIXOS_OZONE_WL=1
ANKI_WAYLAND=1

# --- Editor ---
EDITOR=nvim

# --- PATH ---
PATH=$PATH:$HOME/.local/bin:$HOME/scripts:$XDG_DATA_HOME/cargo/bin
LUA_PATH=$HOME/dotfiles/?.lua;$HOME/dotfiles/?/init.lua;;

# --- Tools ---
NAVI_PATH=$HOME/dotfiles/navi

# --- Appearance ---
NEOVIDE_FRAMELESS=true
NEOVIDE_FRAME=none

# --- XDG Ninja ---
CUDA_CACHE_PATH=$XDG_CACHE_HOME/nv
WINEPREFIX=$XDG_DATA_HOME/wine
RBENV_ROOT=$XDG_DATA_HOME/rbenv
BUNDLE_USER_CONFIG=$XDG_CONFIG_HOME/bundle
BUNDLE_USER_CACHE=$XDG_CACHE_HOME/bundle
BUNDLE_USER_PLUGIN=$XDG_DATA_HOME/bundle
PYENV_ROOT=$XDG_DATA_HOME/pyenv
GOPATH=$XDG_DATA_HOME/go
ANDROID_USER_HOME=$XDG_DATA_HOME/android
ANDROID_HOME=$XDG_DATA_HOME/android/sdk
ANDROID_AVD_HOME=$XDG_DATA_HOME/android/avd
PYTHON_HISTORY=$XDG_STATE_HOME/python_history
NODE_REPL_HISTORY="$XDG_STATE_HOME"/node_repl_history
GRADLE_USER_HOME=$XDG_DATA_HOME/gradle
GNUPGHOME=$XDG_DATA_HOME/gnupg
RUSTUP_HOME=$XDG_DATA_HOME/rustup
CARGO_HOME=$XDG_DATA_HOME/cargo
NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm
NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME"/npm/config/npm-init.js
PSQL_HISTORY=$XDG_STATE_HOME/psql_history
DOTNET_CLI_HOME=$XDG_DATA_HOME/dotnet
DVDCSS_CACHE=$XDG_DATA_HOME/dvdcss
XCOMPOSECACHE=$XDG_CACHE_HOME/X11/xcompose
HISTFILE=$XDG_STATE_HOME/bash/history
ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors
