# shellcheck disable=all
# --- XDG ---
XDG_DATA_HOME=$HOME/.local/share
XDG_CONFIG_HOME=$HOME/.config
XDG_STATE_HOME=$HOME/.local/state
XDG_CACHE_HOME=$HOME/.cache

NIXOS_OZONE_WL=1
ANKI_WAYLAND=1

# --- Editor ---
EDITOR=nvim

# --- PATH ---
PATH=$PATH:$HOME/.local/bin:$HOME/scripts:$HOME/.cargo/bin

# --- Tools ---
NAVI_PATH=$HOME/dotfiles/navi

# --- Appearance ---
NEOVIDE_FRAMELESS=true
NEOVIDE_FRAME=none

