preload = ~/Pictures/wallpaper6.png
preload = ~/Pictures/wallpaper3.png
preload = ~/Pictures/wallpaper5.png

wallpaper = HDMI-A-1, ~/Pictures/wallpaper5.png
wallpaper = DP-2, ~/Pictures/wallpaper3.png
wallpaper = DP-3, ~/Pictures/wallpaper6.png
