# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "{{ teal }}" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "{{ yellow }}", bold = true, italic = true, underline = true }
find_position = { fg = "{{ pink }}", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "{{ green }}", bg = "{{ green }}" }
marker_cut      = { fg = "{{ red }}", bg = "{{ red }}" }
marker_marked   = { fg = "{{ teal }}", bg = "{{ teal }}" }
marker_selected = { fg = "{{ yellow }}", bg = "{{ yellow }}" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "{{ base }}", bg = "{{ green }}" }
count_cut      = { fg = "{{ base }}", bg = "{{ red }}" }
count_selected = { fg = "{{ base }}", bg = "{{ yellow }}" }

# Border
border_symbol = "│"
border_style  = { fg = "{{ overlay1 }}" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "{{ base }}", bg = "{{ blue }}", bold = true }
normal_alt  = { fg = "{{ blue }}", bg = "{{ surface0 }}" }

# Select mode
select_main = { fg = "{{ base }}", bg = "{{ green }}", bold = true }
select_alt  = { fg = "{{ green }}", bg = "{{ surface0 }}" }

# Unset mode
unset_main = { fg = "{{ base }}", bg = "{{ flamingo }}", bold = true }
unset_alt  = { fg = "{{ flamingo }}", bg = "{{ surface0 }}" }

# : }}}


# : Status bar {{{

[status]
separator_open  = ""
separator_close = ""

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "{{ blue }}", bg = "{{ surface1 }}" }
progress_error  = { fg = "{{ red }}", bg = "{{ surface1 }}" }

# Permissions
perm_sep   = { fg = "{{ overlay1 }}" }
perm_type  = { fg = "{{ blue }}" }
perm_read  = { fg = "{{ yellow }}" }
perm_write = { fg = "{{ red }}" }
perm_exec  = { fg = "{{ green }}" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "{{ blue }}" }
active   = { fg = "{{ pink }}", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "{{ blue }}" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "{{ blue }}" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "{{ blue }}" }
title   = {}
hovered = { fg = "{{ pink }}", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "{{ surface0 }}" }
cand            = { fg = "{{ teal }}" }
rest            = { fg = "{{ overlay2 }}" }
desc            = { fg = "{{ pink }}" }
separator       = "  "
separator_style = { fg = "{{ surface2 }}" }

# : }}}


# : Help {{{

[help]
on      = { fg = "{{ teal }}" }
run     = { fg = "{{ pink }}" }
hovered = { reversed = true, bold = true }
footer  = { fg = "{{ surface0 }}", bg = "{{ text }}" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "{{ green }}" }
title_warn  = { fg = "{{ yellow }}" }
title_error = { fg = "{{ red }}" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "{{ teal }}" },

	# Media
	{ mime = "{audio,video}/*", fg = "{{ yellow }}" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "{{ pink }}" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "{{ green }}" },

	# Fallback
	{ name = "*", fg = "{{ text }}" },
	{ name = "*/", fg = "{{ blue }}" }
]

# : }}}
