# copy from .config/monitors.xml
''
  <monitors version="2">
    <configuration>
      <layoutmode>physical</layoutmode>
      <logicalmonitor>
        <x>3840</x>
        <y>0</y>
        <scale>1</scale>
        <monitor>
          <monitorspec>
            <connector>DP-2</connector>
            <vendor>SAM</vendor>
            <product>C24F390</product>
            <serial>HTQKB02246</serial>
          </monitorspec>
          <mode>
            <width>1920</width>
            <height>1080</height>
            <rate>60.000</rate>
          </mode>
        </monitor>
      </logicalmonitor>
      <logicalmonitor>
        <x>1920</x>
        <y>0</y>
        <scale>1</scale>
        <primary>yes</primary>
        <monitor>
          <monitorspec>
            <connector>HDMI-1</connector>
            <vendor>XMI</vendor>
            <product>Mi Monitor</product>
            <serial>5790020009701</serial>
          </monitorspec>
          <mode>
            <width>1920</width>
            <height>1080</height>
            <rate>180.000</rate>
          </mode>
        </monitor>
      </logicalmonitor>
      <logicalmonitor>
        <x>0</x>
        <y>0</y>
        <scale>1</scale>
        <monitor>
          <monitorspec>
            <connector>DP-3</connector>
            <vendor>WAM</vendor>
            <product>AIO25G</product>
            <serial>0x00000001</serial>
          </monitorspec>
          <mode>
            <width>1920</width>
            <height>1080</height>
            <rate>164.999</rate>
          </mode>
        </monitor>
      </logicalmonitor>
    </configuration>
  </monitors>
''
