{
  pkgs,
  inputs,
  system,
  ...
}:
{
  environment.systemPackages = with pkgs; [
    vim
    wget
    neovim
    git
    fastfetch
    kitty
    stow
    tmux
    age
    fzf
    lazygit
    fish
    starship
    yazi
    eza
    zoxide
    navi
    sesh
    bat
    fd
    dust
    duf
    cronie
    syncthing
    gcc
    nodejs
    go
    ruby
    python3
    rustup
    unzip
    zulu
    gnumake
    pnpm
    vscode
    nixfmt
    just
    dpkg
    mission-center
    google-chrome
    discord
    prismlauncher
    obsidian
    obs-studio
    anki
    antimicrox
    handbrake
    qbittorrent
    keepassxc
    gimp3-with-plugins
    papirus-icon-theme
    shotcut
    vlc
    gnome-tweaks
    bibata-cursors
    hypridle
    hyprshot
    wl-clipboard
    libsecret
    lssecret
    neovide
    cloudflared
    lazydocker
    xdg-utils
    flatpak
    gst_all_1.gstreamer
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-bad
    gst_all_1.gst-plugins-ugly
    gst_all_1.gst-libav
    gst_all_1.gst-vaapi
    ripgrep
    pulseaudioFull
    pavucontrol
    kdePackages.qt6ct
    btop
    jq
    cliphist
    mpv
    walker
    libnotify
    xwayland-satellite
    slurp
    satty
    grim
    adw-gtk3
    amdgpu_top
    spotify
    ollama
    microsoft-edge
    ffmpeg
    nixd
    kdlfmt
    devenv
    chezmoi
    deno
    uv
    protonup-qt
    bottles
    tree-sitter
    difftastic
    statix
    footage
    zoom-us
    kdePackages.kdenlive
    kotlin
    gradle
    jetbrains.idea
    android-studio
    file-roller
    clang-tools
    cloudflare-warp
    sqlite
    beekeeper-studio
    android-tools
    gpu-screen-recorder
    opencode
    tree
    gnomeExtensions.vitals
    inputs.nix-alien.packages.${system}.nix-alien
    inputs.agenix.packages.${system}.default
    inputs.thorium.packages.${system}.thorium-avx2
    inputs.fhs.packages.${system}.default
    inputs.noctalia.packages.${system}.default
  ];
}
