{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    basedpyright
    bash-language-server
    biome
    cargo
    clang-tools
    cmake-format
    deno
    devenv
    difftastic
    docker-compose-language-service
    dockerfile-language-server
    gcc
    gnumake
    go
    gofumpt
    golangci-lint
    gopls
    gotools
    hadolint
    jdt-language-server
    kdlfmt
    kotlin-language-server
    ktfmt
    ktlint
    (lua.withPackages (ps: [
      ps.cjson
      ps.luaposix
      ps.lyaml
    ]))
    lua-language-server
    luau
    luau-lsp
    lune
    markdown-toc
    markdownlint-cli2
    marksman
    neocmakelsp
    nil
    nixd
    nixfmt
    nixfmt-tree
    nodejs
    oxfmt
    oxlint
    pnpm
    powershell
    prettier
    python3
    ruby
    ruff
    rustc
    shellcheck
    shfmt
    sqlfluff
    sqlite
    statix
    stylua
    tailwindcss-language-server
    taplo
    tree-sitter
    typescript-go
    uv
    vscode-langservers-extracted
    vtsls
    vue-language-server
    yaml-language-server
  ];
}
